# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23114d9fac23f561a1bd1b5ac9d162b1de84a6bddf25cf7c11543158f122bd3f2917d836c278512ac03dd88bbf0f3646c59b4a9d2c1df439d92029b066e9e50b

test:
  secret_key_base: 3ba09feda9af8502968e7111ddcea2aafbf5628016826bd4ab09e47c0a2fd820d36c117e4aaaed70f8f8128788784272d48ee5cabe49749db916134da6a612a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
